- name: Configuración SSHVPN | Se crea demonio para levantar el tunel de conexión en el servidor cliente
  template:
    src: ssh-tunel.service.j2
    dest: /etc/systemd/system/ssh-tunnel.service
    mode: '0644'
    owner: root
    group: root
  vars:
    tunel_name: "{{ tun_name }}"
    ssh_user: "yagami"
    server_ip: "{{ server }}"
    tunel_any: "{{ tun_name[-1] }}"
  delegate_to: "{{ cliente }}"

- name: Configuración SSHVPN | Se crea interface de tunnel en ambos servidores.
  template:
    src: tun0.nmconnection.j2
    dest: /etc/NetworkManager/system-connections/tun0.nmconnection
    owner: root
    group: root
    mode: '0600'
  notify:
    - "Recargar systemd"
    - "Reiniciar servicio de NetworkManager"
    - "Habilitar e iniciar servicio de tunel"
  delegate_to: "{{ item }}"
  loop:
    - "{{ server }}"
    - "{{ cliente }}"
  vars:
    target: "{{ item }}"

- meta: flush_handlers
...
